/* Generated by scripts/bolt_edge/gen.py -- do not edit. */
#include <lk/console_cmd.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

struct bolt_edge_case {
    const char *name;
    uint32_t (*fn)(uint32_t);
};

#include "cases.inc"

/* FNV-1a over the little-endian results, as in docs/bolt_edge/manifest.json. */
static uint32_t run_case(const struct bolt_edge_case *c) {
    uint32_t h = 0x811c9dc5u;
    for (size_t i = 0; i < sizeof(inputs) / sizeof(inputs[0]); i++) {
        uint32_t v = c->fn(inputs[i]);
        for (int b = 0; b < 4; b++) {
            h ^= (v >> (8 * b)) & 0xff;
            h *= 16777619u;
        }
    }
    return h;
}

static int cmd_bolt_edge(int argc, const console_cmd_args *argv) {
    unsigned n = 0;
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        if (argc > 1 && strcmp(argv[1].str, "all") && strcmp(argv[1].str, cases[i].name))
            continue;
        printf("bolt_edge: %s sink=0x%08x\n", cases[i].name, run_case(&cases[i]));
        n++;
    }
    printf("bolt_edge: done %u cases\n", n);
    return 0;
}

STATIC_COMMAND_START
STATIC_COMMAND("bolt_edge", "R17 edge-case workloads: bolt_edge all|<case>", &cmd_bolt_edge)
STATIC_COMMAND_END(bolt_edge);
