/* Generated by scripts/bolt_edge/gen.py -- do not edit. */
#include <stdint.h>
static __attribute__((noinline)) uint32_t dup(uint32_t x) { return x * 3u + 1u; }
uint32_t edge_dup_a(uint32_t x) { return dup(x) ^ 0x55u; }
