# Generated by scripts/bolt_edge/gen.py -- do not edit.
LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

MODULE_DEPS += lib/console

MODULE_SRCS += \
	$(LOCAL_DIR)/bolt_edge.c \
	$(LOCAL_DIR)/cases.S \
	$(LOCAL_DIR)/edge_c.c \
	$(LOCAL_DIR)/edge_dup_a.c \
	$(LOCAL_DIR)/edge_dup_b.c \

# No FPU/NEON anywhere (project rule).
MODULE_COMPILEFLAGS += -mfpu=none

include make/module.mk
