# Generated by scripts/bolt_edge/gen.py -- do not edit.
# rpi4-bolt-test plus the R17 bolt_edge app (bolt_bench keeps wdog/sample/dump).
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := rpi4

MODULES += \
	app/shell \
	app/bolt_bench \
	app/bolt_edge
