/* Generated by scripts/bolt_edge/gen.py -- do not edit. */
#include <stdint.h>
#include <stdlib.h>
#include <lk/debug.h>

 uint32_t c_switch_marm_o2(uint32_t x) {
    switch (x & 7) {
    case 0: return x + 3;
    case 1: return x * 5;
    case 2: return x ^ 0x5a5a5a5au;
    case 3: return x - 11;
    case 4: return (x << 3) | 1;
    case 5: return x >> 2;
    case 6: return ~x;
    default: return 77;
    }
}
 uint32_t c_loop_marm_o2(uint32_t x) {
    uint32_t acc = 0;
    for (uint32_t i = 0; i < 16; i++) acc += i ^ x;
    return acc;
}
 __attribute__((noinline)) static uint32_t fib_marm_o2(uint32_t n) {
    return n < 2 ? n : fib_marm_o2(n - 1) + fib_marm_o2(n - 2);
}
 uint32_t c_fib_marm_o2(uint32_t x) { return fib_marm_o2(x & 15); }
 static uint32_t op0_marm_o2(uint32_t x) { return x + 1; }
 static uint32_t op1_marm_o2(uint32_t x) { return x * 3; }
 static uint32_t op2_marm_o2(uint32_t x) { return x ^ 0xffu; }
 static uint32_t op3_marm_o2(uint32_t x) { return x >> 1; }
static uint32_t (*const ops_marm_o2[4])(uint32_t) = {op0_marm_o2, op1_marm_o2, op2_marm_o2, op3_marm_o2};
 uint32_t c_indirect_marm_o2(uint32_t x) { return ops_marm_o2[x & 3](x); }
 uint32_t c_noret_marm_o2(uint32_t x) {
    if (x == 0xdead0000u)
        panic("bolt_edge: noreturn path taken\n");
    return x * 7;
}

__attribute__((minsize)) uint32_t c_switch_marm_os(uint32_t x) {
    switch (x & 7) {
    case 0: return x + 3;
    case 1: return x * 5;
    case 2: return x ^ 0x5a5a5a5au;
    case 3: return x - 11;
    case 4: return (x << 3) | 1;
    case 5: return x >> 2;
    case 6: return ~x;
    default: return 77;
    }
}
__attribute__((minsize)) uint32_t c_loop_marm_os(uint32_t x) {
    uint32_t acc = 0;
    for (uint32_t i = 0; i < 16; i++) acc += i ^ x;
    return acc;
}
__attribute__((minsize)) __attribute__((noinline)) static uint32_t fib_marm_os(uint32_t n) {
    return n < 2 ? n : fib_marm_os(n - 1) + fib_marm_os(n - 2);
}
__attribute__((minsize)) uint32_t c_fib_marm_os(uint32_t x) { return fib_marm_os(x & 15); }
__attribute__((minsize)) static uint32_t op0_marm_os(uint32_t x) { return x + 1; }
__attribute__((minsize)) static uint32_t op1_marm_os(uint32_t x) { return x * 3; }
__attribute__((minsize)) static uint32_t op2_marm_os(uint32_t x) { return x ^ 0xffu; }
__attribute__((minsize)) static uint32_t op3_marm_os(uint32_t x) { return x >> 1; }
static uint32_t (*const ops_marm_os[4])(uint32_t) = {op0_marm_os, op1_marm_os, op2_marm_os, op3_marm_os};
__attribute__((minsize)) uint32_t c_indirect_marm_os(uint32_t x) { return ops_marm_os[x & 3](x); }
__attribute__((minsize)) uint32_t c_noret_marm_os(uint32_t x) {
    if (x == 0xdead0000u)
        panic("bolt_edge: noreturn path taken\n");
    return x * 7;
}

__attribute__((optnone, noinline)) uint32_t c_switch_marm_o0(uint32_t x) {
    switch (x & 7) {
    case 0: return x + 3;
    case 1: return x * 5;
    case 2: return x ^ 0x5a5a5a5au;
    case 3: return x - 11;
    case 4: return (x << 3) | 1;
    case 5: return x >> 2;
    case 6: return ~x;
    default: return 77;
    }
}
__attribute__((optnone, noinline)) uint32_t c_loop_marm_o0(uint32_t x) {
    uint32_t acc = 0;
    for (uint32_t i = 0; i < 16; i++) acc += i ^ x;
    return acc;
}
__attribute__((optnone, noinline)) __attribute__((noinline)) static uint32_t fib_marm_o0(uint32_t n) {
    return n < 2 ? n : fib_marm_o0(n - 1) + fib_marm_o0(n - 2);
}
__attribute__((optnone, noinline)) uint32_t c_fib_marm_o0(uint32_t x) { return fib_marm_o0(x & 15); }
__attribute__((optnone, noinline)) static uint32_t op0_marm_o0(uint32_t x) { return x + 1; }
__attribute__((optnone, noinline)) static uint32_t op1_marm_o0(uint32_t x) { return x * 3; }
__attribute__((optnone, noinline)) static uint32_t op2_marm_o0(uint32_t x) { return x ^ 0xffu; }
__attribute__((optnone, noinline)) static uint32_t op3_marm_o0(uint32_t x) { return x >> 1; }
static uint32_t (*const ops_marm_o0[4])(uint32_t) = {op0_marm_o0, op1_marm_o0, op2_marm_o0, op3_marm_o0};
__attribute__((optnone, noinline)) uint32_t c_indirect_marm_o0(uint32_t x) { return ops_marm_o0[x & 3](x); }
__attribute__((optnone, noinline)) uint32_t c_noret_marm_o0(uint32_t x) {
    if (x == 0xdead0000u)
        panic("bolt_edge: noreturn path taken\n");
    return x * 7;
}
