# Generated by scripts/bolt_edge/gen.py -- do not edit.
# Whole-module -marm build of the bolt_edge C cases.
LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

MODULE_SRCS += $(LOCAL_DIR)/edge_cflag.c

MODULE_COMPILEFLAGS += -marm -mfpu=none

include make/module.mk
